use isolated_build in tox.ini
The isolated_build option is required when pyproject.toml is present.
Add it to fix the following tox error:

```
ERROR: pyproject.toml file found.
To use a PEP 517 build-backend you are required to configure tox to use an isolated_build:
https://tox.readthedocs.io/en/latest/example/package.html
```